; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
include_dir = .

[env:rp2350b]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = generic_rp2350
framework = arduino
board_build.core = earlephilhower
board_build.variant = generic_rp2350
board_build.chip = rp2350b
board_build.filesystem_size = 2m
board_upload.maximum_size = 14671872
board_build.f_cpu = 150000000L
build_flags = 
	-DUSE_TINYUSB=0
	-DPICO_STACK_SIZE=8192
lib_deps = 
	bblanchon/ArduinoJson@^7.0.0
	arduino-libraries/NTPClient@^3.2.1
	sensirion/Sensirion I2C SHT4x@^1.1.0
	adafruit/Adafruit NeoPixel@^1.15.0
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.0
	sensirion/Sensirion I2C SCD4x@^1.1.0
upload_protocol = picotool
monitor_speed = 115200
